### ISSUE TITLE
support of double-bounded variables

### ISSUE THREAD

**Issue by paschubert** [mckib2/scikit-glpk#11]
in `_utils.py`:

    def _convert_bounds(processed_bounds):
    ....
        elif ub < lb:
            # lb <= x <= ub
            bounds[ii] = (GLPK.GLP_DB, lb, ub)
    ...
    return bounds

should be changed to:

    def _convert_bounds(processed_bounds):
    ....
        elif lb < ub:
            # lb <= x <= ub
            bounds[ii] = (GLPK.GLP_DB, lb, ub)
    ...
    return bounds

Regards

Peter

**Comment by mckib2** [comment]
@paschubert Good catch -- I'll have time to make this change later in the evening.  Feel free to make a PR if you can get to it before me.
