### ISSUE TITLE
v0.4.4 fill prob error

### ISSUE THREAD

**Issue by ascrookes** [mckib2/scikit-glpk#22]
The upgrade to v0.4.4 breaks some code paths. 

[This PR adds an integrality argument to `_fill_prob`](https://github.com/mckib2/scikit-glpk/commit/81a531b564426ec54982e66f7f32bb429afb4661). That argument is not passed into `_fill_prob` from the `glpk` function. That makes it so [this line](https://github.com/mckib2/scikit-glpk/blob/81a531b564426ec54982e66f7f32bb429afb4661/glpk/_glpk.py#L275) raises an exception when called.

Can this be patched in an upcoming release or is there a workaround that can be used?

Thanks

**Comment by mckib2** [comment]
Hi @ascrookes , thanks for the issue report. I also just ran into this the other day. It's due to an upstream SciPy change with the new MIP handling. I'll try to have a fix and release a new version tonight

**Comment by ascrookes** [comment]
Hi @mckib2, amazing! Thank you for the extremely quick response on this.

**Comment by mckib2** [comment]
@ascrookes New wheels are on PyPI: https://pypi.org/project/scikit-glpk/#files

Please let me know if you are still running into issues or something else broke.  I also noticed we weren't using the latest version of GLPK, so I updated the compiled extension.
