### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Midnighter** [mckib2/scikit-glpk#8]
Hi,

I see in your description that you note the GPL as a reason against making use of existing GLPK wrappers. I was wondering if you have clarity on the licensing issue. Our conclusion so far has been that if you need to compile your program including GLPK headers you actually have no choice but to use the GPL for your project as well.

**Comment by mckib2** [comment]
@Midnighter The intention is to separate the wrapper files and GLPK itself under different licenses (MIT and GPL, respectively).  I agree that this is not clear from the README and probably needs some work.  Also I am not an expert in licensing issues so I could be persuaded that the entire project needs to be GPL'd regardless, but I'm hoping that it's possible to separate the wrapper code from GLPK.

I'll have some time to look at this more tonight, but a resource that may be helpful is this: https://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html

**Comment by Midnighter** [comment]
Okay, thank you. I'm certainly not trying to convince you that it needs to be GPL. Just lacked the legal advice myself so far that would make me feel comfortable doing it in the way that you suggest.

**Comment by mckib2** [comment]
@Midnighter Will the licensing choice either way prevent you from using this package?

@mdhaber The original idea I had was to include the wrapper in scipy, but that's probably not necessary, right?  Could just optionally import scikit-glpk if the user has it installed.  Would it be okay to do the easy thing and switch the license to GPL or would it be worthwhile to separate licensing between wrapper and GLPK code?

**Comment by Midnighter** [comment]
It was more curiosity. At the moment, we use https://github.com/biosustain/swiglpk in https://github.com/opencobra/optlang but I'm not convinced SWIG is still the best solution and I was looking around how others may have solved the build process. Then I saw your note on licensing and it struck home since I had also been thinking about it.

The GPL doesn't stop us from using swiglpk but your goal here rather seems to be to provide some higher level functions to scipy whereas we already have the interface we need in optlang.

P.S.: Feel free to close the discussion at any point :wink:

**Comment by mdhaber** [comment]
We don't need to include the wrapper in SciPy, right. We currently call scikit-umfpack and scikit-sparse as optional dependencies. No reason to build the wrapper in; we can call scikit-glpk.

**Comment by mckib2** [comment]
Alright, I will switch the license to GPL to avoid unnecessarily complicating licensing.  I think the real utility of the package (for me at least) is the linprog-like interface.

@Midnighter Thanks for bringing this up.  Please feel free to open up any other issues you encounter.
